# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ulab/Desktop/craddockEE316/craddockEE316.cache/wt [current_project]
set_property parent.project_path C:/Users/ulab/Desktop/craddockEE316/craddockEE316.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files -quiet c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM.dcp
set_property used_in_implementation false [get_files c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/ADC_Controller.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/pwm.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/UART.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/RAM_Controller.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/clk1Mhz.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/btn_debounce_toggle.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/multiplex_UART.vhd
  C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/imports/testFolder/top_level.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/constrs_1/imports/test2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/constrs_1/imports/test2/Nexys4_Master.xdc]


synth_design -top top_level -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
