# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.cache/wt} [current_project]
set_property parent.project_path {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files {{C:/Users/ulab/Documents/James Bruska/project_2/MyROM.coe}}
add_files {{C:/Users/ulab/Documents/James Bruska/project_2b/MyROM.coe}}
add_files -quiet {{c:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/ip/blk_mem_LUT/blk_mem_LUT.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/ip/blk_mem_LUT/blk_mem_LUT.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/i2c_master_2.1.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/univ_bin_counter.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/TTL_Serial_Display.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/sys_clk.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/SPI_Display.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/reset_delay.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/Nexys4_Display.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/clk_enabler.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/btn_debounce_toggle.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/Interfacer.vhd}
  {C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/sources_1/imports/Downloads/top_level.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ulab/Documents/James Bruska/project_2b/project_2b.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}]


synth_design -top top_level -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
