# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM.xci
# IP: The module: 'sig1dualRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig1dualRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM.xci
# IP: The module: 'sig1dualRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ulab/Desktop/craddockEE316/craddockEE316.srcs/sources_1/ip/sig1dualRAM/sig1dualRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sig1dualRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
